
#
# This action *WILL REQUIRE* to do the checkout before (as it is used from the same repository).
#
name: Gradle
description: Run a Gradle build executing the supplied tasks.

inputs:
  java:
    description: Java version used to run Gradle.
    required: true
    default: "17"

  tasks:
    description: Gradle tasks to execute.
    required: true
    default: build

  token:
    description: Token used to install GraalVM.
    required: true

runs:
  using: composite
  steps:

    # SET UP
    - uses: graalvm/setup-graalvm@v1
      with:
        version: latest
        java-version: ${{ inputs.java }}
        github-token: ${{ inputs.token }}
        components: native-image,llvm
        cache: gradle

    # PROCESS
    - run: ./gradlew ${{ inputs.tasks }}
      shell: bash
    - if: failure()
      run: ./gradlew --info --stacktrace -Pagent ${{ inputs.tasks }}
      shell: bash
