
#disabling strict mode https://github.com/squidfunk/mkdocs-material/issues/1691
#may be truly fixed in future releases.
strict: false
dev_addr: 127.0.0.1:8000

site_name: Hexagon
site_url: https://hexagonkt.com
site_author: Juanjo Aguililla
site_dir: build
site_description: The atoms of your platform

copyright: >
  Made with <svg class="fa-heart" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M462.3 62.6C407.5 15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8 53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1 53-154.3-9.8-207.9z"></path></svg> by
  <a href="https://github.com/hexagonkt/hexagon/graphs/contributors">OSS contributors</a>. Licensed
  under <a href="https://github.com/hexagonkt/hexagon/blob/master/license.md">MIT License</a>

repo_name: GitHub
repo_url: https://github.com/hexagonkt/hexagon
edit_uri: edit/master/hexagon_site/pages

google_analytics: [ UA-48216810-3, auto ]

docs_dir: content

markdown_extensions:
  - meta
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.superfences
  - codehilite:
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: True
      baselevel: 2

nav:
  - Getting Started:
    - Home: index.md
    - Quick Start: quick_start.md
    - Developer Guide: developer_guide.md
    - Core: hexagon_core/hexagon_core.md
    - HTTP Server: port_http_server/port_http_server.md
    - HTTP Client: port_http_client/port_http_client.md
#    - Templates: port_templates/port_templates.md
    - Gradle Helpers: gradle.md
    - Maven Parent POM: maven.md
  - Documentation:
    - Modules:
      - Core: hexagon_core/index.md
      - Scheduler: hexagon_scheduler/index.md
      - Web: hexagon_web/index.md
    - Ports:
      - HTTP Server: port_http_server/index.md
      - HTTP Client: port_http_client/index.md
      - Templates: port_templates/index.md
      - Store (beta): port_store/index.md
      - Messaging (beta): port_messaging/index.md
    - Adapters:
      - HTTP Server:
        - Jetty: http_server_jetty/index.md
        - Servlet: http_server_servlet/index.md
      - HTTP Client:
        - Async HTTP Client: http_client_ahc/index.md
      - Templates:
        - Pebble: templates_pebble/index.md
        - FreeMarker: templates_freemarker/index.md
      - Store (beta):
        - MongoDB (beta): store_mongodb/index.md
      - Messaging (beta):
        - RabbitMQ (beta): messaging_rabbitmq/index.md
    - API: api.md
#  - Guides:
#    - Mutual TLS: guides/mtls.md
  - Examples:
    - Example Projects: examples/example_projects.md
    - Code Examples:
      - HTTP Server: examples/http_server_examples.md
      - HTTP Client: examples/http_client_examples.md
#      - Templates: examples/templates_examples.md
  - Community:
    - Help and Support: help.md
    - Planning: planning.md
    - Contributing: contributing.md
    - GitHub ↗: https://github.com/hexagonkt
    - Dev.to ↗: https://dev.to/hexagonkt
    - LibHunt ↗: https://kotlin.libhunt.com/hexagon-alternatives
    - StackShare ↗: https://stackshare.io/hexagon

theme:
  name: material
  custom_dir: mkdocs

  logo: img/logo_white.svg
  favicon: favicon.ico
  icon:
    repo: fontawesome/brands/github-alt

  features:
    - tabs

  palette:
    primary: indigo
    accent: indigo

  font:
    text: Titillium Web
    code: Roboto Mono

extra_css:
  - css/mkdocs_palette.css
  - css/mkdocs.css

extra_javascript:
  - https://buttons.github.io/buttons.js
  - https://platform.twitter.com/widgets.js

extra:
  repo: hexagonkt/hexagon
  theme_color: '#135AA1'
  site_keywords: Hexagon, microservices, Kotlin, RabbitMQ, MongoDB, JVM, Web, Toolkit, Framework
  site_long_description: >
    Hexagon is a microservices toolkit written in Kotlin. Its purpose is to ease the building of
    services (Web applications, APIs or queue consumers) that run inside a cloud platform

  twitter_user: hexagon_kt
  disqus: hexagonkt-com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hexagonkt/hexagon
    - icon: fontawesome/brands/dev
      link: https://dev.to/hexagonkt
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hexagon_kt
    - icon: fontawesome/brands/slack
      link: https://kotlinlang.slack.com/messages/hexagon
