
name: Build

on:
  push:
    branches-ignore: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      java: 20.0.1
      check_directory: core/build
