
on:
  push:
    branches-ignore: [ master ]

permissions:
  contents: read

jobs:
  build:
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      check_directory: core/build
