
name: Build

on:
  push:
    branches-ignore: [ master ]

jobs:
  build:
    name: Build
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      version: 22.3.1
      java: 19
      check_directory: core/build
