
name: Native

on:
  push:
    branches: [ feature/native ]

jobs:
  native_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Native Test
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      os: ${{ matrix.os }}
      tasks: nativeTest
