
name: Nightly

on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      os: ${{ matrix.os }}
      check_directory: core/build
      ref: develop

  sample_keystores:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Sample Keystores (${{ matrix.os }})
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      os: ${{ matrix.os }}
      ref: develop
      tasks: createCa createIdentities

  build_site:
    name: Build Site
    permissions: read-all
    uses: hexagonkt/hexagon/.github/workflows/site.yml@master
    with:
      ref: develop

  test_publishing:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      os: ${{ matrix.os }}
      ref: develop
      check_directory: core/build
      tasks: publishToMavenLocal -x test
