
name: Nightly

on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          exempt-issue-assignees: jaguililla
          days-before-stale: 90
          days-before-close: 14
          days-before-pr-close: -1
          stale-pr-message: This PR is stale because it has been open 45 days with no activity.
          stale-issue-message:
            "This issue is stale because it has been open 90 days with no activity. Remove stale
            label or comment or this will be closed in 14 days."
          close-issue-message:
            "This issue was closed because it has been stalled for 14 days with no activity."

  build:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Build Project
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Build
        run: ls -AlF core/build

  sample_keystores:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Sample Keystores (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Create Sample Keystores
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tasks: createCa createIdentities

  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Install ImageMagick
        uses: ./.github/actions/image_magick
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages

      # PROCESS
      - name: Build Project
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Site
        run: |
          ./gradlew --info -x build buildSite
          ls -AlF site/build/site

  test_publishing:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Install Java
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: native-image,llvm
          cache: gradle

      - name: Test Publishing
        run: |
          ./gradlew --info -x test -Pagent build
          [[ $graalvm_metadata == true ]] && ./gradlew --info -x test metadataCopy
          ./gradlew --info -x test publishToMavenLocal
