
name: Nightly

on:
  schedule:
    - cron: "59 23 * * *"

permissions:
  contents: read

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          exempt-issue-labels: pinned
          include-only-assigned: true
          days-before-pr-close: -1
          stale-pr-message: This PR is stale because it has been open 60 days with no activity.
          stale-issue-message:
            "This issue is stale because it has been open 60 days with no activity. Remove stale
            label or comment or this will be closed in 7 days."
          close-issue-message:
            "This issue was closed because it has been stalled for 7 days with no activity."

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    name: Build (${{ matrix.os }})
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      os: ${{ matrix.os }}
      java: 20
      check_directory: core/build
      ref: develop

  # TODO Delete this special case when Jacoco runs on macOS properly
  build_macos:
    name: Build (macos-latest)
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      os: macos-latest
      java: 20
      check_directory: core/build
      ref: develop
      tasks: -x jacocoTestReport

  sample_keystores:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Sample Keystores (${{ matrix.os }})
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      os: ${{ matrix.os }}
      java: 20
      ref: develop
      tasks: createCa createIdentities

  native_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Native Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure Page File
        uses: al-cheb/configure-pagefile-action@v1.3
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          minimum-size: 16GB
          disk-root: "C:"
      - name: Check Out
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Set Up Java
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 20
          distribution: graalvm-community
          cache: gradle
      - name: Build Project
        run: ./gradlew --info --stacktrace nativeTest

  build_site:
    name: Build Site
    uses: hexagonkt/hexagon/.github/workflows/site.yml@master
    with:
      ref: develop

  test_publishing:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      os: ${{ matrix.os }}
      java: 20
      ref: develop
      check_directory: core/build
      tasks: publishToMavenLocal -x test
