
name: Nightly

on:
  push:
    branches-ignore:
      - master
#  schedule:
#    - cron: "59 23 * * *"

jobs:
  build:
    continue-on-error: true
    defaults:
      run: { shell: bash }
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v2
#        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v2
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Build Project
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew --warn --console=plain build
      - name: Log Build (ON FAILURE)
        if: matrix.os == 'ubuntu-latest' && failure()
        run: ./gradlew --info --console=plain --stacktrace build
      - name: Build Project WITHOUT Docker
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew --warn --console=plain build -x store_mongodb:test -x messaging_rabbitmq:test
      - name: Log Build WITHOUT Docker (ON FAILURE)
        if: matrix.os != 'ubuntu-latest' && failure()
        run: >
          ./gradlew --info --console=plain --stacktrace build
          -x store_mongodb:test -x messaging_rabbitmq:test

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}

  sample_keystores:
    defaults:
      run: { shell: bash }
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Sample Keystores (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v2
#        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v2
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Create Sample Keystores
        run: ./gradlew --warn --console=plain --no-daemon createCa createIdentities

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}

  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v2
#        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v2
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Build Site
        run: |
          ./gradlew --warn --console=plain --no-daemon build dokkaGfm
          ./gradlew --warn --console=plain --no-daemon -x test buildSite

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}

  test_publishing:
    defaults:
      run: { shell: bash }
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v2
#        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v2
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Test Publishing
        run: ./gradlew --warn --console=plain --no-daemon publishToMavenLocal

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}
