
name: Nightly

on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      os: ${{ matrix.os }}
      check_directory: core/build
      ref: develop

  sample_keystores:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Sample Keystores (${{ matrix.os }})
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      os: ${{ matrix.os }}
      ref: develop
      check_directory: core/build
      tasks: createCa createIdentities

  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages
      - name: Install ImageMagick
        uses: ./.github/actions/image_magick

      # PROCESS
      - name: Build Project
        uses: ./.github/actions/gradle
      - name: Build Site
        run: |
          ./gradlew --info -x build buildSite
          ls -AlF site/build/site

  test_publishing:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      os: ${{ matrix.os }}
      ref: develop
      check_directory: core/build
      tasks: publishToMavenLocal -x test
