
name: Nightly

on:
#  schedule:
#    - cron: "59 23 * * *"
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v2
#        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v2
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Build Project
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew --warn --console=plain build
        shell: bash
      - name: Log Build (ON FAILURE)
        if: matrix.os == 'ubuntu-latest' && failure()
        run: ./gradlew --info --console=plain --stacktrace build
        shell: bash
      - name: Build Project WITHOUT Docker
        if: matrix.os != 'ubuntu-latest'
        run: ./gradlew --warn --console=plain build -x store_mongodb:test -x messaging_rabbitmq:test
        shell: bash
      - name: Log Build WITHOUT Docker (ON FAILURE)
        if: matrix.os != 'ubuntu-latest' && failure()
        run: >
          ./gradlew --info --console=plain --stacktrace build
          -x store_mongodb:test -x messaging_rabbitmq:test
        shell: bash

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}
        shell: bash

  sample_keystores:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Sample Keystores (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v2
#        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v2
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Create Sample Keystores
        run: ./gradlew --warn --console=plain --no-daemon createCa createIdentities
        shell: bash

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}
        shell: bash

  build_site:
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    name: Build Site (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v2
#        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v2
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Build Site
        shell: bash
        run: |
          ./gradlew --warn --console=plain --no-daemon build dokkaGfm
          ./gradlew --warn --console=plain --no-daemon -x test buildSite

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}
        shell: bash

  test_publishing:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v2
#        with: { ref: develop }
      - name: Install Java
        uses: actions/setup-java@v2
        with: { java-version: 11, distribution: adopt }
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Test Publishing
        run: ./gradlew --warn --console=plain --no-daemon publishToMavenLocal
        shell: bash

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}
        shell: bash
