
name: Nightly

on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  nightly:
    name: Nightly
    runs-on: ubuntu-latest

    steps:
      # SET UP
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # BUILD
      - name: Build Project
        run: ./gradlew --warn --console=plain build

      - name: Create Sample Keystores
        run: ./gradlew --warn --console=plain createCa createIdentities

      - name: Build Site
        run: ./gradlew --no-daemon --warn --console=plain buildSite

      - name: Test Publishing
        run: ./gradlew --no-daemon --warn --console=plain publishToMavenLocal

      - name: Log Build (ON FAILURE)
        if: failure()
        run: ./gradlew --info --stacktrace --console=plain build
