
name: Pull Request

on:
  - pull_request

jobs:
  sample_keystores:
    name: Sample Keystores
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Create Sample Keystores
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tasks: createCa createIdentities

  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install ImageMagick
        uses: ./.github/actions/image_magick
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages

      # PROCESS
      - name: Build Project
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Site
        run: |
          ./gradlew --info -x build buildSite
          ls -AlF site/build/site

  test_publishing:
    name: Test Publishing
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install Java
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: 17
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: native-image,llvm
          cache: gradle
      - name: Test Publishing
        run: |
          ./gradlew --info -x test -Pagent build
          ./gradlew --info -x test metadataCopy
          ./gradlew --info -x test publishToMavenLocal
