
name: Pull Request

on:
  - pull_request

jobs:
  sample_keystores:
    name: Sample Keystores
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      version: 22.3.1
      java: 19
      tasks: createCa createIdentities

  native_test:
    name: Native Test
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      version: 22.3.1
      java: 19
      tasks: nativeTest

  build_site:
    name: Build Site
    permissions: read-all
    uses: hexagonkt/hexagon/.github/workflows/site.yml@master
    with:
      version: 22.3.1

  test_publishing:
    name: Test Publishing
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      version: 22.3.1
      java: 19
      check_directory: core/build
      tasks: publishToMavenLocal -x test
