
name: Pull Request

on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Build Project
        uses: ./.github/actions/gradle

  sample_keystores:
    name: Sample Keystores
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Create Sample Keystores
        uses: ./.github/actions/gradle
        with:
          tasks: createCa createIdentities

  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v2
        with: { java-version: 17, distribution: temurin }
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      # PROCESS
      - name: Build Site
        run: |
          ./gradlew --no-daemon build
          ./gradlew --no-daemon -x build buildSite

      # CLEAN UP
      - name: Clean Gradle Cache
        run: rm -f ~/.gradle/caches/modules-2/{modules-2.lock,gc.properties}

  test_publishing:
    name: Test Publishing
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Test Publishing
        uses: ./.github/actions/gradle
        with:
          tasks: --no-daemon publishToMavenLocal -x test
