
on: pull_request

permissions:
  contents: read

jobs:
  sample_keystores:
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      java: dev
      distribution: graalvm
      tasks: createCa createIdentities

  native_test:
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      java: dev
      distribution: graalvm
      tasks: nativeTest

  jmh:
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      java: dev
      distribution: graalvm
      tasks: jmh

  build_site:
    uses: hexagonkt/hexagon/.github/workflows/site.yml@develop

  test_publishing:
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      java: dev
      distribution: graalvm
      check_directory: core/build
      tasks: publishToMavenLocal -x test
