
name: Pull Request

on:
  - pull_request

jobs:
  sample_keystores:
    name: Sample Keystores
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      check_directory: core/build
      tasks: createCa createIdentities

  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    permissions: read-all
    uses: hexagonkt/hexagon/.github/workflows/site.yml@develop

  test_publishing:
    name: Test Publishing
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      check_directory: core/build
      tasks: publishToMavenLocal -x test
