
name: Pull Request

on:
  - pull_request

permissions:
  contents: read

jobs:
  sample_keystores:
    name: Sample Keystores
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      java: dev
      distribution: graalvm
      tasks: createCa createIdentities

  native_test:
    name: Native Test
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      java: dev
      distribution: graalvm
      tasks: nativeTest

  jmh:
    name: JMH Benchmark
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      java: dev
      distribution: graalvm
      tasks: jmh

  build_site:
    name: Build Site
    uses: hexagonkt/hexagon/.github/workflows/site.yml@develop

  test_publishing:
    name: Test Publishing
    uses: hexagonkt/.github/.github/workflows/graalvm_gradle.yml@master
    with:
      java: dev
      distribution: graalvm
      check_directory: core/build
      tasks: publishToMavenLocal -x test
