
name: Pull Request

on:
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Build
        run: ls -AlF core/build

  sample_keystores:
    name: Sample Keystores
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Create Sample Keystores
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tasks: createCa createIdentities

  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
      - name: Install ImageMagick
        uses: ./.github/actions/image_magick
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages

      # PROCESS
      - name: Build Project
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Site
        run: |
          ./gradlew --info -x build buildSite
          ls -AlF site/build/site

  test_publishing:
    name: Test Publishing
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Agent Test
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy Metadata
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tasks: metadataCopy -x test
      - name: Test Publishing
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tasks: publishToMavenLocal -x test
