
name: Pull Request

on:
  - pull_request

jobs:
  sample_keystores:
    name: Sample Keystores
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      tasks: createCa createIdentities

  build_site:
    name: Build Site
    runs-on: ubuntu-latest
    steps:

      # SET UP
      - name: Check Out
        uses: actions/checkout@v3
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages
      - name: Install ImageMagick
        uses: ./.github/actions/image_magick

      # PROCESS
      - name: Build Project
        uses: ./.github/actions/gradle
      - name: Build Site
        run: |
          ./gradlew --info -x build buildSite
          ls -AlF site/build/site

  test_publishing:
    name: Test Publishing
    permissions: read-all
    uses: hexagonkt/.github/.github/workflows/gradle.yml@master
    with:
      tasks: publishToMavenLocal -x test
