
name: Push

on:
  push:
    branches-ignore: [ master, release/** ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/gradle
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Build
        run: ls -AlF core/build
