
name: Release Branch

on:
  push:
    branches: [ release/** ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

      - name: Check Out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Java
        uses: graalvm/setup-graalvm@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Publish Packages
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew --info build
          ./gradlew --info --no-daemon -x test release
