
name: Release

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Restore ImageMagick Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-imagemagick-${{ hashFiles('assets/*.gradle*') }}
          restore-keys: ${{ runner.os }}-imagemagick-
          path: ~/.local/bin/magick

      - name: Install ImageMagick
        run: |
          sudo apt-get install fuse
          sudo apt-get install librsvg2-bin
          mkdir -p ~/.local/bin
          export MAGICK="https://download.imagemagick.org/ImageMagick/download/binaries/magick"
          [[ ! -f ~/.local/bin/magick ]] && sudo curl "$MAGICK" -Lo ~/.local/bin/magick
          sudo chmod +x ~/.local/bin/magick
          magick --version

      - name: Restore MkDocs Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages

      - name: Check Out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export REMOTE="https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git remote set-url origin "$REMOTE"
          git config --global user.email "juanjoaguililla@gmail.com"
          git config --global user.name "jaguililla"
          git clone "$REMOTE" --branch gh-pages build/gh-pages
          ./gradlew --info build
          ./gradlew --info -x build buildSite
          ls -AlF site/build/site

      - name: Publish Packages
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew --info --no-daemon -x test release

      - name: Publish Site
        run: |
          cp -rf site/build/site/* build/gh-pages/
          cd build/gh-pages
          git add --all
          git commit -m "Publishing to gh-pages"
          git push origin gh-pages
