
on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  scheduled:
    name: Scheduled
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: develop
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build & Test
        run: .github/pre-push.sh
