
on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  scheduled:
    name: Scheduled
    runs-on: ubuntu-latest

    steps:
      # SET UP
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: develop

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # BUILD
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build & Test
        run: .github/pre-push.sh

      - name: Set up Tests Reports (ON FAILURE)
        if: failure()
        run: |
          mkdir build/test
          find . -type f -wholename "*/build/*/*/TEST-*.xml" -exec cp {} build/test \;

      - name: Upload Tests Reports (ON FAILURE)
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test_reports
          path: build/test
