
on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  scheduled:
    name: Scheduled
    runs-on: ubuntu-latest

    steps:
      # SET UP
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: develop

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # BUILD
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: All Checks
        run: |
          alias gw='./gradlew --warn --quiet --console plain'

          # Build and check all artifacts
          gw build
          gw createCa createIdentities
          gw buildSite
          gw tfb

          # Test publishing
          gw publish -PbintrayDryRun=true

          # Build and start containers required for tests and benchmarks
          alias dc='docker-compose --log-level warning'
          export COMPOSE_FILE="docker-compose.yml:hexagon_benchmark/docker-compose.yml"
          dc rm -sfv
          dc up -d --build

      - name: Set up Tests Reports (ON FAILURE)
        if: failure()
        run: |
          mkdir build/test
          find . -type f -wholename "*/build/*/*/TEST-*.xml" -exec cp {} build/test \;

      - name: Upload Tests Reports (ON FAILURE)
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test_reports
          path: build/test
