
on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
#      - run: .github/pre-push.sh
#      - env:
#          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
#        run: |
#          echo "REF> $GITHUB_REF"
#          export BRANCH=$(echo "$GITHUB_REF" | sed -e "s/refs\/heads\///")
#          echo "BRANCH> $BRANCH"
#          ./gradlew --console=plain --quiet --no-daemon -x test sonarqube
