
on:
  schedule:
    - cron: "59 23 * * *"

jobs:
  schedule:
    name: Schedule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: .github/pre-push.sh
