
name: Site

on:
  workflow_call:
    inputs:
      check_directory:
        type: string
        description: Directory to check for build execution.
        default: site/build/site

jobs:
  site:
    name: Build Site
    runs-on: ubuntu-latest
    defaults:
      run: { shell: bash }
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages
      - name: Install ImageMagick
        uses: ./.github/actions/image_magick
      - name: Check Out
        uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/gradle
      - name: Build Site
        run: ./gradlew --info -x build buildSite
      - name: Check Build
        if: ${{ inputs.check_directory != '' }}
        run: ls -AlF "${{ inputs.check_directory }}"
