
name: Site

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Branch to check out.
        default: ''

      java:
        type: string
        description: Java version used to run Gradle.
        default: "17"

      check_directory:
        type: string
        description: Directory to check for build execution.
        default: site/build/site

jobs:
  site:
    name: Build Site
    runs-on: ubuntu-latest
    defaults:
      run: { shell: bash }
    steps:
      - name: Restore MkDocs Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages

      - name: Check Out
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set Up Java
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: ${{ inputs.java }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: gradle

      - name: Build Project
        run: ./gradlew build

      - name: Diagnose Build
        if: failure()
        run: ./gradlew --info --stacktrace build

      - name: Build Site
        run: ./gradlew --info --stacktrace -x build buildSite

      - name: Check Build
        if: ${{ inputs.check_directory != '' }}
        run: ls -AlF "${{ inputs.check_directory }}"
